# Generated by Django 4.2.2 on 2023-06-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionProductoTeleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condición Producto Teleco',
                'verbose_name_plural': 'Condiciones Productos Telecomunicaciones',
            },
        ),
        migrations.CreateModel(
            name='FormaEnvioProductoTeleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forma Envío Producto Teleco',
                'verbose_name_plural': 'Formas Envío Productos Telecomunicaciones',
            },
        ),
        migrations.CreateModel(
            name='MarcaProductoTeleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes/categorias')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca Producto Teleco',
                'verbose_name_plural': 'Marcas Productos Telecomunicaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoConexRouterTeleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Conexión Swith Teleco',
                'verbose_name_plural': 'Tipos Conexiones Swithes Telecomunicaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoGarantiaProductoTeleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Garatía Producto Teleco',
                'verbose_name_plural': 'Tipos Garantía Productos Telecomunicaciones',
            },
        ),
        migrations.CreateModel(
            name='ProductoSwitchTeleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=250, unique=True)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('codigo_universal', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000)),
                ('retiro_en_persona', models.BooleanField(default=False)),
                ('tiempo_garantia', models.IntegerField()),
                ('unidad_garantia', models.CharField(max_length=20, unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes/productos_teleco')),
                ('modelo', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('puntos_incluidos', models.IntegerField()),
                ('serie', models.CharField(max_length=20)),
                ('tipo_telecomunicacion', models.CharField(max_length=50)),
                ('capacidad_telecomunicacion', models.IntegerField()),
                ('unidad_capacida_teleco', models.IntegerField()),
                ('es_gestionable', models.BooleanField(default=False)),
                ('condicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.condicionproductoteleco')),
                ('forma_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.formaenvioproductoteleco')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.marcaproductoteleco')),
                ('tipo_garantia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.tipogarantiaproductoteleco')),
            ],
            options={
                'verbose_name': 'Producto Switch Teleco',
                'verbose_name_plural': 'Productos Switches Telecomunicaciones',
            },
        ),
        migrations.CreateModel(
            name='ProductoRouterTeleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=250, unique=True)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('codigo_universal', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000)),
                ('retiro_en_persona', models.BooleanField(default=False)),
                ('tiempo_garantia', models.IntegerField()),
                ('unidad_garantia', models.CharField(max_length=20, unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes/productos_teleco')),
                ('modelo', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unidades_x_paquete', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('voltaje', models.CharField(max_length=100)),
                ('con_conexion_poe', models.BooleanField(default=False)),
                ('funciones', models.CharField(max_length=2000)),
                ('velocidad_inalambrica', models.IntegerField()),
                ('unidad_velocidad', models.CharField(max_length=20)),
                ('frecuencias', models.CharField(max_length=200)),
                ('tipo_frecuencia', models.CharField(max_length=100)),
                ('cant_antenas_ext', models.IntegerField()),
                ('cant_antenas_int', models.IntegerField()),
                ('condicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.condicionproductoteleco')),
                ('forma_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.formaenvioproductoteleco')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.marcaproductoteleco')),
                ('tipo_conexion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.tipoconexrouterteleco')),
                ('tipo_garantia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.tipogarantiaproductoteleco')),
            ],
            options={
                'verbose_name': 'Producto Router Teleco',
                'verbose_name_plural': 'Productos Router Telecomunicaciones',
            },
        ),
        migrations.CreateModel(
            name='ProductoOtroTeleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=250, unique=True)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('codigo_universal', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000)),
                ('retiro_en_persona', models.BooleanField(default=False)),
                ('tiempo_garantia', models.IntegerField()),
                ('unidad_garantia', models.CharField(max_length=20, unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes/productos_teleco')),
                ('modelo', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ficha_tecnica', models.CharField(max_length=2000)),
                ('condicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.condicionproductoteleco')),
                ('forma_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.formaenvioproductoteleco')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.marcaproductoteleco')),
                ('tipo_garantia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telecomunicaciones_app.tipogarantiaproductoteleco')),
            ],
            options={
                'verbose_name': 'Otro Producto Teleco',
                'verbose_name_plural': 'Otros Productos Telecomunicaciones',
            },
        ),
    ]
