# Generated by Django 4.2.2 on 2023-06-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecomunicaciones_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoswitchteleco',
            old_name='unidad_capacida_teleco',
            new_name='unidad_capacidad_teleco',
        ),
    ]
