# Generated by Django 4.2.2 on 2023-06-27 14:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecomunicaciones_app', '0003_alter_productootroteleco_unidad_garantia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productootroteleco',
            name='ficha_tecnica',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
